{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-metadata-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-api-1.0.0-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "eef4377ad318010a8d1fac4ec6d927620147aa97eaec163ef791e5a150bccdf8e3a8f2ac3b4068ed604d3676baf873aa891d55520113149a2511e37c4b015bf3",
          "sha256": "f59684268347c3474dfb479154d3f59b25f140d1b8faffeb062217ffcef58688",
          "sha1": "6ccf4687219b7d9ceafc6cb0ac75dd34c7638b6f",
          "md5": "8be27f9e3eacb53885d12545c7bf854c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "subsonic-api-kotlin-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-1.0.0-SNAPSHOT-sources.jar",
          "size": 29936,
          "sha512": "c4fe339f4878626bfff8fba5e425ba03843173b18183666c194bedb4ec0bd1ae0bf4016ae3472c262d1da7e6161113b9562e50e714da384e066f2a8a09b3b06f",
          "sha256": "6e1e56d7fc8c7f7653add61b80598280a06d69146ebd4e61dc460359d50ca123",
          "sha1": "a94f6a25e9f2947640bec0687954a1d2a7e05f13",
          "md5": "49ced3497ffde48d1beff3011ab0e6b7"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-SNAPSHOT/subsonic-api-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-SNAPSHOT/subsonic-api-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-SNAPSHOT/subsonic-api-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-SNAPSHOT/subsonic-api-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-SNAPSHOT/subsonic-api-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-SNAPSHOT/subsonic-api-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-SNAPSHOT/subsonic-api-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-SNAPSHOT/subsonic-api-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-SNAPSHOT/subsonic-api-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-SNAPSHOT/subsonic-api-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-SNAPSHOT/subsonic-api-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-SNAPSHOT/subsonic-api-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxarm64/1.0.0-SNAPSHOT/subsonic-api-linuxarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxarm64/1.0.0-SNAPSHOT/subsonic-api-linuxarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxx64/1.0.0-SNAPSHOT/subsonic-api-linuxx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxx64/1.0.0-SNAPSHOT/subsonic-api-linuxx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-SNAPSHOT/subsonic-api-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-SNAPSHOT/subsonic-api-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-SNAPSHOT/subsonic-api-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-mingwx64/1.0.0-SNAPSHOT/subsonic-api-mingwx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-mingwx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-mingwx64/1.0.0-SNAPSHOT/subsonic-api-mingwx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-mingwx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-SNAPSHOT/subsonic-api-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-SNAPSHOT/subsonic-api-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-SNAPSHOT/subsonic-api-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-SNAPSHOT/subsonic-api-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-SNAPSHOT/subsonic-api-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-SNAPSHOT/subsonic-api-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-SNAPSHOT/subsonic-api-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-SNAPSHOT/subsonic-api-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-SNAPSHOT/subsonic-api-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-SNAPSHOT/subsonic-api-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-SNAPSHOT/subsonic-api-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-SNAPSHOT/subsonic-api-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
