{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-metadata-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-api-1.0.0-SNAPSHOT.jar",
          "size": 46076,
          "sha512": "c0e6a87427e405f679a1a40490c097b831b22d6d7f9cf79c17c06a850a868123bc2086f0789ea7f137db653c08cd12234629019f2d628b74d767e7fdf1efb209",
          "sha256": "abebf5da3106493b1c4b0baa3be1852e450e9cefc2311988680c9a66519501f7",
          "sha1": "df3395fe7b67a119e0a4ef5452a96ab92192f7b3",
          "md5": "302ef13a7ae16b6c51e66fe646bb92f3"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "subsonic-api-kotlin-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-1.0.0-SNAPSHOT-sources.jar",
          "size": 29936,
          "sha512": "826de82b3a73c35376c69e3342679a32a42da040de591271a84edfda908a241b2a49c03597551ab1cd59c19b1fb79ca1e106875432e43e9a68b6b2dd694f5f30",
          "sha256": "97cef69307922c301451e04a7aefb9120bc8aed7905a5e1d940a72b29579ebd7",
          "sha1": "0a4c9448f01820e4f3262f871377353fbde13929",
          "md5": "58290657ed717c362d5a4c20c8300cfc"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-SNAPSHOT/subsonic-api-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-SNAPSHOT/subsonic-api-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-SNAPSHOT/subsonic-api-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-SNAPSHOT/subsonic-api-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-SNAPSHOT/subsonic-api-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-SNAPSHOT/subsonic-api-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-SNAPSHOT/subsonic-api-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-SNAPSHOT/subsonic-api-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-SNAPSHOT/subsonic-api-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-SNAPSHOT/subsonic-api-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-SNAPSHOT/subsonic-api-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-SNAPSHOT/subsonic-api-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxarm64/1.0.0-SNAPSHOT/subsonic-api-linuxarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxarm64/1.0.0-SNAPSHOT/subsonic-api-linuxarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxx64/1.0.0-SNAPSHOT/subsonic-api-linuxx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxx64/1.0.0-SNAPSHOT/subsonic-api-linuxx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-SNAPSHOT/subsonic-api-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-SNAPSHOT/subsonic-api-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-SNAPSHOT/subsonic-api-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-mingwx64/1.0.0-SNAPSHOT/subsonic-api-mingwx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-mingwx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-mingwx64/1.0.0-SNAPSHOT/subsonic-api-mingwx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-mingwx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-SNAPSHOT/subsonic-api-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-SNAPSHOT/subsonic-api-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-SNAPSHOT/subsonic-api-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-SNAPSHOT/subsonic-api-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-SNAPSHOT/subsonic-api-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-SNAPSHOT/subsonic-api-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-SNAPSHOT/subsonic-api-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-SNAPSHOT/subsonic-api-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-SNAPSHOT/subsonic-api-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-SNAPSHOT/subsonic-api-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-SNAPSHOT/subsonic-api-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-SNAPSHOT/subsonic-api-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
