{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-js-1.0.0-SNAPSHOT.klib",
          "size": 316713,
          "sha512": "8b0c14f32261ebe23070a6a2eaa8f8924239bf47c407e3ba8d21b901ea0406b85efeaed52f56e8b146d52396dc7f80bcf0e339bad2625128c4cad926ea57d584",
          "sha256": "3d8429b7f601bb790282f5daf49e077afec9c922a15a5ee1b329e735141432d1",
          "sha1": "aca5127bcc8c6dcf696d98a6da43ad2ad451bfcd",
          "md5": "494f294aa80cae7d8726921b5935908c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-js-1.0.0-SNAPSHOT.klib",
          "size": 316713,
          "sha512": "8b0c14f32261ebe23070a6a2eaa8f8924239bf47c407e3ba8d21b901ea0406b85efeaed52f56e8b146d52396dc7f80bcf0e339bad2625128c4cad926ea57d584",
          "sha256": "3d8429b7f601bb790282f5daf49e077afec9c922a15a5ee1b329e735141432d1",
          "sha1": "aca5127bcc8c6dcf696d98a6da43ad2ad451bfcd",
          "md5": "494f294aa80cae7d8726921b5935908c"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 29720,
          "sha512": "0fcb476498ec9fee6f2863b483981589afbbba2a8353ab5bc9cd4771e3f669c48681e8a1ae9f2466559fc79d0b8e4d2895b7da102b3be433bd516de2d540c5a3",
          "sha256": "901b90b7e4d12899ed9e4349587df3bd0b09871ae08efa120e301e859d2ee466",
          "sha1": "89f083b880e78d3791400f1173d85be677d75be2",
          "md5": "daddd885d185144a059df8655b17cd47"
        }
      ]
    }
  ]
}
