{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-js-1.0.0-SNAPSHOT.klib",
          "size": 316817,
          "sha512": "7f9fdcfe978bf21e212f0c1873a783ec5f7ffa5a14cc9299daef90d96a5bcf7b9d6b1552ab4682c93723b3f36d7817673424df8f8cd001ffd7c9b19917cb6089",
          "sha256": "572b065a5b2e38724b8e5f0a13c642bafca48c704fad16bf691955c5363ff08b",
          "sha1": "398fbdb39e04462fcfe051c520dcccf55d2ffd3e",
          "md5": "acc437376bcb18f1ffecd23166d14d92"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-js-1.0.0-SNAPSHOT.klib",
          "size": 316817,
          "sha512": "7f9fdcfe978bf21e212f0c1873a783ec5f7ffa5a14cc9299daef90d96a5bcf7b9d6b1552ab4682c93723b3f36d7817673424df8f8cd001ffd7c9b19917cb6089",
          "sha256": "572b065a5b2e38724b8e5f0a13c642bafca48c704fad16bf691955c5363ff08b",
          "sha1": "398fbdb39e04462fcfe051c520dcccf55d2ffd3e",
          "md5": "acc437376bcb18f1ffecd23166d14d92"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 29767,
          "sha512": "2bfb981919963dfe03bb8e45eb75e21c09b44a90d99385c9bba4017f85ed4bb5ff3cbd5d1e97d530b580d8ce8a7bf583580533bdb141acc4e3e2b930bb81a8e5",
          "sha256": "26ecd4ec831da4643de54905908a732b0162fe0b14ee066e7be9f80fdc201fc6",
          "sha1": "a1ac70553aa8ebbc6cf278a7d45ab643bca19447",
          "md5": "046dd316a95f201b7b8415d4fc58aa04"
        }
      ]
    }
  ]
}
