{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-client/1.0.0-beta11/subsonic-client-1.0.0-beta11.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-client",
    "version": "1.0.0-beta11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-beta11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-watchosArm32Main-1.0.0-beta11.klib",
          "url": "subsonic-client-watchosarm32-1.0.0-beta11.klib",
          "size": 65905,
          "sha512": "62bd2e76e5055cd7ee0b2c7ca850abf8c790538b7a78aef03a6a98964e009c9b798b722c5987f5b87ff9893fe7b47fd8f89dcaee2f0825a6210d558825f698df",
          "sha256": "44f3a8c885a619ee262b8d59228b68db418582d8e5fac884d000c1991b294aab",
          "sha1": "b3ef0434096f4daa379eaeec4ec371522e8aa2bd",
          "md5": "76168cce0b80634d6022e4632c05b3cb"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-client-watchosarm32-1.0.0-beta11-sources.jar",
          "url": "subsonic-client-watchosarm32-1.0.0-beta11-sources.jar",
          "size": 7650,
          "sha512": "5a698e67bfbce4c658b94311f0382ceeb91c96e8be3fd3ae607cf81fa4667a75858dde79e785f58e504ad9be70f4b1fd55d318c9a391ce16d1fe573a721637a9",
          "sha256": "24ab6f2cd38e1d9ce5842fb8745f420c8d3e9c847d46fb99a4c422f6a29f7f09",
          "sha1": "379f7047ec0970d0501cf2c8f7558fddad7fcf45",
          "md5": "569a37f08aedfce9ededde8d77a452aa"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-beta11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-watchosarm32-1.0.0-beta11-metadata.jar",
          "url": "subsonic-client-watchosarm32-1.0.0-beta11-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
