{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta08/subsonic-api-1.0.0-beta08.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-watchosArm32Main-1.0.0-beta08.klib",
          "url": "subsonic-api-watchosarm32-1.0.0-beta08.klib",
          "size": 302361,
          "sha512": "5038c34bc192103e368e436f9b9a0ec35b3323165b5408d6d8c04a228ecebf385ecbfb11f005794a40ea371827785480962e8b985bcec74e91036bae02368b96",
          "sha256": "44fc61236d182ac4e3bda3eabd690c90f84f00f39fd02ad3bcf573e985147743",
          "sha1": "353bb6655a4a157bf765c3368e545d4f8f2d406d",
          "md5": "6a445aef8a58b459cbc62b4e37928bcf"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-watchosarm32-1.0.0-beta08-sources.jar",
          "url": "subsonic-api-watchosarm32-1.0.0-beta08-sources.jar",
          "size": 27754,
          "sha512": "3af78e9a2b7c6790e8711f54d551a7a43217a1ae0b439720dfa0ef6984950a62cffe97f4e04881c714622c3a0ed2d96a0efe697abf1073174570da5c0b890bd7",
          "sha256": "08eb1ecdb3020ea219457084aaa35175dc4f50c5d56c3c5082d217963a45f951",
          "sha1": "b355696e4dddfea2171feee118c51b2caff9da31",
          "md5": "29a45445145c22f715d143cad7a44006"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-watchosarm32-1.0.0-beta08-metadata.jar",
          "url": "subsonic-api-watchosarm32-1.0.0-beta08-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
