{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-wasm-js-1.0.0-SNAPSHOT.klib",
          "size": 313489,
          "sha512": "6be8241b38d0ae1d21de550b4bf5f839b85d88a33eb93f18ea9a6e946d43e477b72a904257f7e30da4cb25a43e61ebdad0f6486f40894c005e5366cbbe6d18e7",
          "sha256": "aada0516ee45255304df0752fe011fda92c3f01b666750bc744f7866d2ee682f",
          "sha1": "8e29e18bf2ced56fc3dc4bf7ae206594ef4570b7",
          "md5": "6cfe14aa6d5dcf7fbd5bf21bca91563f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-wasm-js-1.0.0-SNAPSHOT.klib",
          "size": 313489,
          "sha512": "6be8241b38d0ae1d21de550b4bf5f839b85d88a33eb93f18ea9a6e946d43e477b72a904257f7e30da4cb25a43e61ebdad0f6486f40894c005e5366cbbe6d18e7",
          "sha256": "aada0516ee45255304df0752fe011fda92c3f01b666750bc744f7866d2ee682f",
          "sha1": "8e29e18bf2ced56fc3dc4bf7ae206594ef4570b7",
          "md5": "6cfe14aa6d5dcf7fbd5bf21bca91563f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-wasm-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 29720,
          "sha512": "0fcb476498ec9fee6f2863b483981589afbbba2a8353ab5bc9cd4771e3f669c48681e8a1ae9f2466559fc79d0b8e4d2895b7da102b3be433bd516de2d540c5a3",
          "sha256": "901b90b7e4d12899ed9e4349587df3bd0b09871ae08efa120e301e859d2ee466",
          "sha1": "89f083b880e78d3791400f1173d85be677d75be2",
          "md5": "daddd885d185144a059df8655b17cd47"
        }
      ]
    }
  ]
}
