{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-wasm-js-1.0.0-SNAPSHOT.klib",
          "size": 313493,
          "sha512": "f480f2c9765cec00b8e2d1d902709472e04d10138511903bb0c6ed271be85fd063c7e1bd8d142e2a00980060e89766083b80ed9a7116b1e1359cc1a7f4abd3a7",
          "sha256": "63e4bc6a2c46ea30ad555625d70e41d5b8e560f1f48cf7da5773610f8ef6e1a5",
          "sha1": "a32a271cb04339134e3db4e46de05e4e88b94919",
          "md5": "73507a7baf7376c4f7df1c06636c0eeb"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-wasm-js-1.0.0-SNAPSHOT.klib",
          "size": 313493,
          "sha512": "f480f2c9765cec00b8e2d1d902709472e04d10138511903bb0c6ed271be85fd063c7e1bd8d142e2a00980060e89766083b80ed9a7116b1e1359cc1a7f4abd3a7",
          "sha256": "63e4bc6a2c46ea30ad555625d70e41d5b8e560f1f48cf7da5773610f8ef6e1a5",
          "sha1": "a32a271cb04339134e3db4e46de05e4e88b94919",
          "md5": "73507a7baf7376c4f7df1c06636c0eeb"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-wasm-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 29757,
          "sha512": "d25bc172e6d05c9159c20f4a9296b57128d527de8750cdbdfcdd5c475b4f1c8fc37e509b571fa17c145e7031e09a53bc925ff6bbb147af958fa8030d5ac99e00",
          "sha256": "9bc8a71ca1e006b768a543bf9de8685450eaf7b215d324f8f96779527399c299",
          "sha1": "8aae24d3b998575c362a9103d02a30f77e458cd3",
          "md5": "f78f0be880e694d6dee2593b89219dcd"
        }
      ]
    }
  ]
}
