{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zt64.subsonic",
    "module": "subsonic-client",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-metadata-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-client-1.0.0-SNAPSHOT.jar",
          "size": 9766,
          "sha512": "bcb6e8b1e53fa109f4203817dda524302b9c8958e15e50c9d26907ed4d3e9c0353f1d00e03bb03ec8998fcdc307c437dabb208777e13a1330bfa80481317c0f6",
          "sha256": "941d7b4a20857b9c80d593e2d691aee432ec40823c8cf276eeee71f464673b1b",
          "sha1": "772e8f583704a3cc7bba288a79c260ad7eac2c6a",
          "md5": "005537287c4251ccf70f177ddc7e5885"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "subsonic-client-kotlin-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-client-1.0.0-SNAPSHOT-sources.jar",
          "size": 8111,
          "sha512": "07f987b598ee52922cfb43df267ea27afd203d5c32105deadfddff10abefab66ae162cf6033f8b323fb327a9e7a90855165cdbce86a8a5fcf469b5475489e01c",
          "sha256": "bcdcbcb8710aed2258a6d15526a8a4372c6e3f7a4aa6dcde4400b06301621c49",
          "sha1": "6891f5fcdde933ced85d7abec673994bdeebea05",
          "md5": "941f5221af6044d51c4aed46d8ff18c5"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosarm64/1.0.0-SNAPSHOT/subsonic-client-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosarm64/1.0.0-SNAPSHOT/subsonic-client-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosarm64/1.0.0-SNAPSHOT/subsonic-client-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosx64/1.0.0-SNAPSHOT/subsonic-client-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosx64/1.0.0-SNAPSHOT/subsonic-client-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosx64/1.0.0-SNAPSHOT/subsonic-client-iosx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-js/1.0.0-SNAPSHOT/subsonic-client-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-js/1.0.0-SNAPSHOT/subsonic-client-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-js/1.0.0-SNAPSHOT/subsonic-client-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-client-jvm/1.0.0-SNAPSHOT/subsonic-client-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-client-jvm/1.0.0-SNAPSHOT/subsonic-client-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-client-jvm/1.0.0-SNAPSHOT/subsonic-client-jvm-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-linuxarm64/1.0.0-SNAPSHOT/subsonic-client-linuxarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-linuxarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-linuxarm64/1.0.0-SNAPSHOT/subsonic-client-linuxarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-linuxarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-linuxx64/1.0.0-SNAPSHOT/subsonic-client-linuxx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-linuxx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-linuxx64/1.0.0-SNAPSHOT/subsonic-client-linuxx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-linuxx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-macosarm64/1.0.0-SNAPSHOT/subsonic-client-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-macosarm64/1.0.0-SNAPSHOT/subsonic-client-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-macosarm64/1.0.0-SNAPSHOT/subsonic-client-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-mingwx64/1.0.0-SNAPSHOT/subsonic-client-mingwx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-mingwx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-mingwx64/1.0.0-SNAPSHOT/subsonic-client-mingwx64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-mingwx64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvosarm64/1.0.0-SNAPSHOT/subsonic-client-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvosarm64/1.0.0-SNAPSHOT/subsonic-client-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvosarm64/1.0.0-SNAPSHOT/subsonic-client-tvosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-tvossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-wasm-js/1.0.0-SNAPSHOT/subsonic-client-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-wasm-js/1.0.0-SNAPSHOT/subsonic-client-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-wasm-js/1.0.0-SNAPSHOT/subsonic-client-wasm-js-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-wasm-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm32/1.0.0-SNAPSHOT/subsonic-client-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm32/1.0.0-SNAPSHOT/subsonic-client-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm32/1.0.0-SNAPSHOT/subsonic-client-watchosarm32-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm32",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm64/1.0.0-SNAPSHOT/subsonic-client-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm64/1.0.0-SNAPSHOT/subsonic-client-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm64/1.0.0-SNAPSHOT/subsonic-client-watchosarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchossimulatorarm64/1.0.0-SNAPSHOT/subsonic-client-watchossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
