{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-linuxArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-linuxarm64-1.0.0-SNAPSHOT.klib",
          "size": 329444,
          "sha512": "381ee2a5a55eb1951176793ecf3ff4a76fe3ce982ccd77b9b5851547595fcf82a3225f7ea49d91942f950b444423cf8d6a14c540a7bbcaf27a9d981594098c79",
          "sha256": "f4c054eda5e69f8a94ce13e7d8f90cc707c47c793b3e1c2f6fb82e90a659fbc3",
          "sha1": "eb95243d90520563612eba367e6afe5fa991c9d3",
          "md5": "98ccd670762daecee5f796c61a839ab8"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-linuxarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-linuxarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 29757,
          "sha512": "d25bc172e6d05c9159c20f4a9296b57128d527de8750cdbdfcdd5c475b4f1c8fc37e509b571fa17c145e7031e09a53bc925ff6bbb147af958fa8030d5ac99e00",
          "sha256": "9bc8a71ca1e006b768a543bf9de8685450eaf7b215d324f8f96779527399c299",
          "sha1": "8aae24d3b998575c362a9103d02a30f77e458cd3",
          "md5": "f78f0be880e694d6dee2593b89219dcd"
        }
      ]
    }
  ]
}
