{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta11/subsonic-api-1.0.0-beta11.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-beta11.klib",
          "url": "subsonic-api-wasm-js-1.0.0-beta11.klib",
          "size": 313581,
          "sha512": "fd515afd46d68d0d66450cc8c6cc167a592de6b3dd55922c9c557ca8aad28933fd8bc2ce1ecbba59281c3e2be9710658c6c9b0560d36b53aed34d0fb883f142c",
          "sha256": "ecaeeb7c7a5eb0065815413309973cf2ff35f989661260cfee7cf4ff94237886",
          "sha1": "ce7acb5b218b6d3dde613d330c1489ee3cf284ed",
          "md5": "dd0debc3c3be3240d5b09b8a2199ed1d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-beta11.klib",
          "url": "subsonic-api-wasm-js-1.0.0-beta11.klib",
          "size": 313581,
          "sha512": "fd515afd46d68d0d66450cc8c6cc167a592de6b3dd55922c9c557ca8aad28933fd8bc2ce1ecbba59281c3e2be9710658c6c9b0560d36b53aed34d0fb883f142c",
          "sha256": "ecaeeb7c7a5eb0065815413309973cf2ff35f989661260cfee7cf4ff94237886",
          "sha1": "ce7acb5b218b6d3dde613d330c1489ee3cf284ed",
          "md5": "dd0debc3c3be3240d5b09b8a2199ed1d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-beta11-sources.jar",
          "url": "subsonic-api-wasm-js-1.0.0-beta11-sources.jar",
          "size": 29767,
          "sha512": "2bfb981919963dfe03bb8e45eb75e21c09b44a90d99385c9bba4017f85ed4bb5ff3cbd5d1e97d530b580d8ce8a7bf583580533bdb141acc4e3e2b930bb81a8e5",
          "sha256": "26ecd4ec831da4643de54905908a732b0162fe0b14ee066e7be9f80fdc201fc6",
          "sha1": "a1ac70553aa8ebbc6cf278a7d45ab643bca19447",
          "md5": "046dd316a95f201b7b8415d4fc58aa04"
        }
      ]
    }
  ]
}
