{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-client/1.0.0-beta11/subsonic-client-1.0.0-beta11.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-client",
    "version": "1.0.0-beta11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-beta11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-jvm-1.0.0-beta11.jar",
          "url": "subsonic-client-jvm-1.0.0-beta11.jar",
          "size": 132356,
          "sha512": "23d2b002d0f38124d9e831688d83185c6a84c1c7118ab7fdec6d890eb626b2e64377d2a6c350b07fefb62a086d7e7acb2f9ac445f0df765b350227319401ff5a",
          "sha256": "ffe71d28229495c18eb2a3eb6126755511c0546254da1989610d58b1e6b3d7d0",
          "sha1": "273ba409e29cf99a342a04ed1c1d943044aef761",
          "md5": "9a7f99bf69d9ba1191eaa8796347a302"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-beta11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-jvm-1.0.0-beta11.jar",
          "url": "subsonic-client-jvm-1.0.0-beta11.jar",
          "size": 132356,
          "sha512": "23d2b002d0f38124d9e831688d83185c6a84c1c7118ab7fdec6d890eb626b2e64377d2a6c350b07fefb62a086d7e7acb2f9ac445f0df765b350227319401ff5a",
          "sha256": "ffe71d28229495c18eb2a3eb6126755511c0546254da1989610d58b1e6b3d7d0",
          "sha1": "273ba409e29cf99a342a04ed1c1d943044aef761",
          "md5": "9a7f99bf69d9ba1191eaa8796347a302"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "subsonic-client-jvm-1.0.0-beta11-sources.jar",
          "url": "subsonic-client-jvm-1.0.0-beta11-sources.jar",
          "size": 7650,
          "sha512": "5a698e67bfbce4c658b94311f0382ceeb91c96e8be3fd3ae607cf81fa4667a75858dde79e785f58e504ad9be70f4b1fd55d318c9a391ce16d1fe573a721637a9",
          "sha256": "24ab6f2cd38e1d9ce5842fb8745f420c8d3e9c847d46fb99a4c422f6a29f7f09",
          "sha1": "379f7047ec0970d0501cf2c8f7558fddad7fcf45",
          "md5": "569a37f08aedfce9ededde8d77a452aa"
        }
      ]
    }
  ]
}
