{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-mingwX64Main-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-mingwx64-1.0.0-SNAPSHOT.klib",
          "size": 329465,
          "sha512": "f4b44c743913204ce5fff5db0c2ef246e53ccea901b4fbacbef3c2f2ba061c4be30b1be7af5c4491cdfd6b03a073741e467b4c3dfcae28521745c7a6ccbe3943",
          "sha256": "ff63513e7832e64569593b699b1a3069627b22f8722b8193533e01255267c65a",
          "sha1": "581c6e117b9c72326bbfcb5452bc4e9128bcf533",
          "md5": "a557301bfe64878857a07c8e5fff9c6e"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-mingwx64-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-mingwx64-1.0.0-SNAPSHOT-sources.jar",
          "size": 29772,
          "sha512": "72c0a75f66761c61b93b8a717479e4efc3dfe6683562db3e35f929a13c138bb75b62499ea79bff457568eb64fd0256036107fcb20c2e3d1ac605f368026edb90",
          "sha256": "4c9b2e163fa5b2740339ee5a0517d4049277357ba3f3641cb9ced42a07b1da7e",
          "sha1": "4c840b39d145449e96736ffd39c69c3df0d1c884",
          "md5": "625d137c8dbe6c12322c3bcab67e0363"
        }
      ]
    }
  ]
}
