{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-mingwX64Main-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-mingwx64-1.0.0-SNAPSHOT.klib",
          "size": 329424,
          "sha512": "c94a86d008a5d3c7e93c71c2da1acefd653331e2a7c3024f5bb2b591e9bf8454f78666cdd9ababca00bfe3705c39e2ea0b22aa21e4f49b069ba3a4572f2908e2",
          "sha256": "c92b4227e6c4387a22f18ecbc7a72df88f01edfa2d433eacf95eb8a097f7f23e",
          "sha1": "3dde78d7e94e0a1a6e8e52111914f472a1aa33f6",
          "md5": "6b9fe76b4e4df870d4fde97883b340d3"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-mingwx64-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-mingwx64-1.0.0-SNAPSHOT-sources.jar",
          "size": 29755,
          "sha512": "c85ff7fab8e28a52363829b51b8f4f6eec423bfce36f07a9345b36deda6f53941365ed23f93abdfe38055847b6dab81228be1d2e0e3766aa86dde01938e2da0e",
          "sha256": "0d5a0936edd84356938cee41b44434e2bb16a68731631cd40016cd3d5ca710d5",
          "sha1": "2faf9c47d0a1bec2db6c9b091076ede89cd8a872",
          "md5": "b9d665b7c69217429646a0438b9bc044"
        }
      ]
    }
  ]
}
