{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-watchosSimulatorArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT.klib",
          "size": 333165,
          "sha512": "e9d20b3698e6811ff50a2453caa740ae3ec5dc0c12bbb48453bb642acc71d97380b98e0bd273e10685eb59c3907bb7f04551c53eb7d243f070bc6b9c25b5c8f1",
          "sha256": "f9591eeca7105a0d559bee0cde23b7456f9803ab1f4e515ae515acf08cdc6711",
          "sha1": "38fb9d250200d2ec71d72ba6e5f6534d08b5cba4",
          "md5": "8cef5420cf0a7bb329c7bbfb39923f18"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 29936,
          "sha512": "826de82b3a73c35376c69e3342679a32a42da040de591271a84edfda908a241b2a49c03597551ab1cd59c19b1fb79ca1e106875432e43e9a68b6b2dd694f5f30",
          "sha256": "97cef69307922c301451e04a7aefb9120bc8aed7905a5e1d940a72b29579ebd7",
          "sha1": "0a4c9448f01820e4f3262f871377353fbde13929",
          "md5": "58290657ed717c362d5a4c20c8300cfc"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "subsonic-api-watchossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
