{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-client/1.0.0-beta08/subsonic-client-1.0.0-beta08.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-client",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-linuxArm64Main-1.0.0-beta08.klib",
          "url": "subsonic-client-linuxarm64-1.0.0-beta08.klib",
          "size": 65892,
          "sha512": "9361ed9ac202f173db8474776519044e436cd42f737173741ddead425c3ed003eccb9d8828e2db510ea80686afe01c6cca8294b61185b609b5811efbe443d346",
          "sha256": "69aeccbb95d929640747085946d377bdf059d088db3c4dbcd2c663b2332df7dd",
          "sha1": "1d0c23cead9443d3b8fabb04444fabf74dc61477",
          "md5": "226c23c39b34f023e062f7c7952ee802"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-client-linuxarm64-1.0.0-beta08-sources.jar",
          "url": "subsonic-client-linuxarm64-1.0.0-beta08-sources.jar",
          "size": 7650,
          "sha512": "5a698e67bfbce4c658b94311f0382ceeb91c96e8be3fd3ae607cf81fa4667a75858dde79e785f58e504ad9be70f4b1fd55d318c9a391ce16d1fe573a721637a9",
          "sha256": "24ab6f2cd38e1d9ce5842fb8745f420c8d3e9c847d46fb99a4c422f6a29f7f09",
          "sha1": "379f7047ec0970d0501cf2c8f7558fddad7fcf45",
          "md5": "569a37f08aedfce9ededde8d77a452aa"
        }
      ]
    }
  ]
}
