{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-metadata-1.0.0-beta08.jar",
          "url": "subsonic-api-1.0.0-beta08.jar",
          "size": 43133,
          "sha512": "79c3e9d7fa150ddb841a9e3f7959ebef52b021b785fc8c777de70389e69dc958010ac1eb507dbd965e6c2603c83480119e8b2f33bcf5d5dee860f5016f982a2e",
          "sha256": "faff8094696da71d0496ada7eb9b87fb4716665f06b131b4bc08eb323fc83428",
          "sha1": "4b178ccfec7bb6f544b5019046772bb6e2bf89b8",
          "md5": "b813df4a3d00dacc63226ab9da62d2e5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "subsonic-api-kotlin-1.0.0-beta08-sources.jar",
          "url": "subsonic-api-1.0.0-beta08-sources.jar",
          "size": 27754,
          "sha512": "3af78e9a2b7c6790e8711f54d551a7a43217a1ae0b439720dfa0ef6984950a62cffe97f4e04881c714622c3a0ed2d96a0efe697abf1073174570da5c0b890bd7",
          "sha256": "08eb1ecdb3020ea219457084aaa35175dc4f50c5d56c3c5082d217963a45f951",
          "sha1": "b355696e4dddfea2171feee118c51b2caff9da31",
          "md5": "29a45445145c22f715d143cad7a44006"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-beta08/subsonic-api-iosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-beta08/subsonic-api-iosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-beta08/subsonic-api-iosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-beta08/subsonic-api-iossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-beta08/subsonic-api-iossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-beta08/subsonic-api-iossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-beta08/subsonic-api-iosx64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-beta08/subsonic-api-iosx64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-beta08/subsonic-api-iosx64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-beta08/subsonic-api-js-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-beta08/subsonic-api-js-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-beta08/subsonic-api-js-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-beta08/subsonic-api-jvm-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-beta08/subsonic-api-jvm-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-beta08/subsonic-api-jvm-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxarm64/1.0.0-beta08/subsonic-api-linuxarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxarm64/1.0.0-beta08/subsonic-api-linuxarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxx64/1.0.0-beta08/subsonic-api-linuxx64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxx64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxx64/1.0.0-beta08/subsonic-api-linuxx64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxx64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-beta08/subsonic-api-macosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-beta08/subsonic-api-macosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-beta08/subsonic-api-macosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-mingwx64/1.0.0-beta08/subsonic-api-mingwx64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-mingwx64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-mingwx64/1.0.0-beta08/subsonic-api-mingwx64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-mingwx64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-beta08/subsonic-api-tvosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-beta08/subsonic-api-tvosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-beta08/subsonic-api-tvosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-beta08/subsonic-api-tvossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-beta08/subsonic-api-tvossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-beta08/subsonic-api-tvossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-beta08/subsonic-api-wasm-js-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-beta08/subsonic-api-wasm-js-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-beta08/subsonic-api-wasm-js-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-beta08/subsonic-api-watchosarm32-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-beta08/subsonic-api-watchosarm32-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-beta08/subsonic-api-watchosarm32-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-beta08/subsonic-api-watchosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-beta08/subsonic-api-watchosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-beta08/subsonic-api-watchosarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-beta08/subsonic-api-watchossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-beta08/subsonic-api-watchossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-beta08/subsonic-api-watchossimulatorarm64-1.0.0-beta08.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-beta08"
      }
    }
  ]
}
