{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta10/subsonic-api-1.0.0-beta10.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-beta10.klib",
          "url": "subsonic-api-wasm-js-1.0.0-beta10.klib",
          "size": 313050,
          "sha512": "8c8ca8943475dcd85958e394035313272722816880f99533151a450f343b3bc9339c29e355bb7e32a20205d8a1f1745238c1ac739bf55aae73cb446b72b27c88",
          "sha256": "4234532ed37e3df8a41950a2fc7a0ee47f436561c14d7934aed1cd0112dde3c1",
          "sha1": "3a1e2ffee43753a779c9a28f58cda70175192039",
          "md5": "bbc71a32e5be95c0a518382a2a355175"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-beta10.klib",
          "url": "subsonic-api-wasm-js-1.0.0-beta10.klib",
          "size": 313050,
          "sha512": "8c8ca8943475dcd85958e394035313272722816880f99533151a450f343b3bc9339c29e355bb7e32a20205d8a1f1745238c1ac739bf55aae73cb446b72b27c88",
          "sha256": "4234532ed37e3df8a41950a2fc7a0ee47f436561c14d7934aed1cd0112dde3c1",
          "sha1": "3a1e2ffee43753a779c9a28f58cda70175192039",
          "md5": "bbc71a32e5be95c0a518382a2a355175"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "subsonic-api-wasm-js-1.0.0-beta10-sources.jar",
          "url": "subsonic-api-wasm-js-1.0.0-beta10-sources.jar",
          "size": 29756,
          "sha512": "89ec5d460700dacacda3770fcaabfee39596b855e345195f12b3e184fe478550bb384625b15d07d6758fdd49564961345484d1102563d50fbdc00cd2ecb87156",
          "sha256": "ab4c45d206b5cf7ae055548f429a254f21ceafa54dd2f1fc35f868717a4fd7d9",
          "sha1": "8928b2b4da90a8ad385e2a31204ff617b0d70b72",
          "md5": "51c2fbe7e308d407cfaa076dba6e5233"
        }
      ]
    }
  ]
}
