{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "size": 505366,
          "sha512": "43d4cd36a8258ca3dec501c543c5513b16df7c4daf9e23393203a16622f924a02e49911cc1bcfc8babfcc281fb5d6e130de39e12086265a488a783f71bac178e",
          "sha256": "8ff19665bd5a95b86c776d9dc0139f88ffcde7a0483eb10c917eb2cbfd2b012d",
          "sha1": "7a3d500fa26927633367431456a957c3c855af72",
          "md5": "c25c720a3b67a158b78ab2f0d54073fe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "size": 505366,
          "sha512": "43d4cd36a8258ca3dec501c543c5513b16df7c4daf9e23393203a16622f924a02e49911cc1bcfc8babfcc281fb5d6e130de39e12086265a488a783f71bac178e",
          "sha256": "8ff19665bd5a95b86c776d9dc0139f88ffcde7a0483eb10c917eb2cbfd2b012d",
          "sha1": "7a3d500fa26927633367431456a957c3c855af72",
          "md5": "c25c720a3b67a158b78ab2f0d54073fe"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 29936,
          "sha512": "c4fe339f4878626bfff8fba5e425ba03843173b18183666c194bedb4ec0bd1ae0bf4016ae3472c262d1da7e6161113b9562e50e714da384e066f2a8a09b3b06f",
          "sha256": "6e1e56d7fc8c7f7653add61b80598280a06d69146ebd4e61dc460359d50ca123",
          "sha1": "a94f6a25e9f2947640bec0687954a1d2a7e05f13",
          "md5": "49ced3497ffde48d1beff3011ab0e6b7"
        }
      ]
    }
  ]
}
