{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "size": 502142,
          "sha512": "909ab963818a1eb3c290dda306a827af54001d21fea6d859196f05b87863619d3a4234ffa0c15ac5dc8cd1be32637421292baf40ff750ebcabf78faf1a2ed910",
          "sha256": "2f01f11d7276c820fd7cdcc604fa4745ea56fa321ce192c3de4e00cf541874a3",
          "sha1": "cb77278d518bea97c1a24ebdf1103cf8a6b07a93",
          "md5": "d0a8097cb8465e9cf3e5cea8c2b26d52"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "size": 502142,
          "sha512": "909ab963818a1eb3c290dda306a827af54001d21fea6d859196f05b87863619d3a4234ffa0c15ac5dc8cd1be32637421292baf40ff750ebcabf78faf1a2ed910",
          "sha256": "2f01f11d7276c820fd7cdcc604fa4745ea56fa321ce192c3de4e00cf541874a3",
          "sha1": "cb77278d518bea97c1a24ebdf1103cf8a6b07a93",
          "md5": "d0a8097cb8465e9cf3e5cea8c2b26d52"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 29755,
          "sha512": "c85ff7fab8e28a52363829b51b8f4f6eec423bfce36f07a9345b36deda6f53941365ed23f93abdfe38055847b6dab81228be1d2e0e3766aa86dde01938e2da0e",
          "sha256": "0d5a0936edd84356938cee41b44434e2bb16a68731631cd40016cd3d5ca710d5",
          "sha1": "2faf9c47d0a1bec2db6c9b091076ede89cd8a872",
          "md5": "b9d665b7c69217429646a0438b9bc044"
        }
      ]
    }
  ]
}
