{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-SNAPSHOT/subsonic-api-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "size": 502175,
          "sha512": "4141f35230bf1fc7f54f186f80546209afde751fc0445524c05da63f98eebcdec9f99a30b0e991eae2dc4a70caadca111ed63e9c559384b28531aa2023d7d242",
          "sha256": "ed970a5876ce89ad66721b5f98f2c1e0898ffb77d0fc447fb458ec450afb5b0d",
          "sha1": "0872f9bde6d26690a97c16a5582d5f486238937b",
          "md5": "46e7e6a8e795207559906f2ddfcd197e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT.jar",
          "size": 502175,
          "sha512": "4141f35230bf1fc7f54f186f80546209afde751fc0445524c05da63f98eebcdec9f99a30b0e991eae2dc4a70caadca111ed63e9c559384b28531aa2023d7d242",
          "sha256": "ed970a5876ce89ad66721b5f98f2c1e0898ffb77d0fc447fb458ec450afb5b0d",
          "sha1": "0872f9bde6d26690a97c16a5582d5f486238937b",
          "md5": "46e7e6a8e795207559906f2ddfcd197e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "subsonic-api-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-api-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 29757,
          "sha512": "d25bc172e6d05c9159c20f4a9296b57128d527de8750cdbdfcdd5c475b4f1c8fc37e509b571fa17c145e7031e09a53bc925ff6bbb147af958fa8030d5ac99e00",
          "sha256": "9bc8a71ca1e006b768a543bf9de8685450eaf7b215d324f8f96779527399c299",
          "sha1": "8aae24d3b998575c362a9103d02a30f77e458cd3",
          "md5": "f78f0be880e694d6dee2593b89219dcd"
        }
      ]
    }
  ]
}
