{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta09/subsonic-api-1.0.0-beta09.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-watchosArm32Main-1.0.0-beta09.klib",
          "url": "subsonic-api-watchosarm32-1.0.0-beta09.klib",
          "size": 329171,
          "sha512": "55096260375afa65724a3d5143bca11037ec7d85414f6e4826ca36cb05e3d274dfab3fb940448b34b7f3bff54337b7b68fe2018eadaaa4aaeaa40832d28684a9",
          "sha256": "ea0d36d084471ec10fdc768c280cbe3f8a09a32e0a217769ac1b8b608e620ac3",
          "sha1": "49214f9db820361139b4f775d6e2d6258e77125b",
          "md5": "77973db31170a41bae39e007ee9f2249"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-watchosarm32-1.0.0-beta09-sources.jar",
          "url": "subsonic-api-watchosarm32-1.0.0-beta09-sources.jar",
          "size": 29792,
          "sha512": "9464122ba4ea101afac46f1c8c46e8c8eb7f37edf016ef2078e420ea36ca50ef4aa7baee90c919b50d3230565dbd228048b736dbb8d31893cf8994655e2cdb5f",
          "sha256": "aaf2d0e767767b1e08d45296d29b076a4f1266c9449ba2598a0bb56b4714f11b",
          "sha1": "6f949a29034a5a3c5f699b52bf8973e08edb54cb",
          "md5": "cd483bbe80471160775801fba090f3fc"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-watchosarm32-1.0.0-beta09-metadata.jar",
          "url": "subsonic-api-watchosarm32-1.0.0-beta09-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
