{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta08/subsonic-api-1.0.0-beta08.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-linuxX64Main-1.0.0-beta08.klib",
          "url": "subsonic-api-linuxx64-1.0.0-beta08.klib",
          "size": 302335,
          "sha512": "32155f066eb4d2a1d12f39358e536c34f322745ee8f72727ce22e80f5c72112f83363a55196fc2e22b8e51db265d209274bc8ef4411b64189ef358239451160a",
          "sha256": "512c3ba6240cc08a62d53fc39699e190a3f2fa7d61d1cfa209386cc9b464da81",
          "sha1": "fe8203e4b30c723d3c3b0b5b0695cfb3c5da1b07",
          "md5": "2e3153eaa2890eb603e1abb671b93159"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-linuxx64-1.0.0-beta08-sources.jar",
          "url": "subsonic-api-linuxx64-1.0.0-beta08-sources.jar",
          "size": 27754,
          "sha512": "3af78e9a2b7c6790e8711f54d551a7a43217a1ae0b439720dfa0ef6984950a62cffe97f4e04881c714622c3a0ed2d96a0efe697abf1073174570da5c0b890bd7",
          "sha256": "08eb1ecdb3020ea219457084aaa35175dc4f50c5d56c3c5082d217963a45f951",
          "sha1": "b355696e4dddfea2171feee118c51b2caff9da31",
          "md5": "29a45445145c22f715d143cad7a44006"
        }
      ]
    }
  ]
}
