{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-client/1.0.0-SNAPSHOT/subsonic-client-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-client",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-iosX64Main-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-client-iosx64-1.0.0-SNAPSHOT.klib",
          "size": 67211,
          "sha512": "a90d2415b4bc349c95c64a28b580a4a11133bae3a9e3320fa4070fea4a1f30a0cb5d93b00a1ebe183368e9908afd229d08749594e4b5d7236200005c9c7f0258",
          "sha256": "5874cca89c17285be0fa2ab38c35c014af9dc8b7966197606207dcc3ce65aa12",
          "sha1": "ad65d0c870f5e134d3d1104c6f0866b917e52f18",
          "md5": "368dbc9c46d3247d64778d308d474182"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-client-iosx64-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-client-iosx64-1.0.0-SNAPSHOT-sources.jar",
          "size": 8111,
          "sha512": "07f987b598ee52922cfb43df267ea27afd203d5c32105deadfddff10abefab66ae162cf6033f8b323fb327a9e7a90855165cdbce86a8a5fcf469b5475489e01c",
          "sha256": "bcdcbcb8710aed2258a6d15526a8a4372c6e3f7a4aa6dcde4400b06301621c49",
          "sha1": "6891f5fcdde933ced85d7abec673994bdeebea05",
          "md5": "941f5221af6044d51c4aed46d8ff18c5"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-iosx64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "subsonic-client-iosx64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
