{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-client/1.0.0-SNAPSHOT/subsonic-client-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-client",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-client-js-1.0.0-SNAPSHOT.klib",
          "size": 66231,
          "sha512": "436b4a58694d571640159ee647e955fa3e5c260a97a28699903d40ccb6247a27f982cb371c0463c9acb1f25697498e4fcba0217ef85de506a1484c94171e4ac4",
          "sha256": "cdd69b03c63527975a6de3741d3e33b4923dc630ace20bc558bd44fa93525312",
          "sha1": "46fb23406e8283e83cec1cdfc03abdd8b61f8188",
          "md5": "e4b1b74a716a74badef735c0a46dccf9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-js-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-client-js-1.0.0-SNAPSHOT.klib",
          "size": 66231,
          "sha512": "436b4a58694d571640159ee647e955fa3e5c260a97a28699903d40ccb6247a27f982cb371c0463c9acb1f25697498e4fcba0217ef85de506a1484c94171e4ac4",
          "sha256": "cdd69b03c63527975a6de3741d3e33b4923dc630ace20bc558bd44fa93525312",
          "sha1": "46fb23406e8283e83cec1cdfc03abdd8b61f8188",
          "md5": "e4b1b74a716a74badef735c0a46dccf9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "subsonic-client-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-client-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 8111,
          "sha512": "07f987b598ee52922cfb43df267ea27afd203d5c32105deadfddff10abefab66ae162cf6033f8b323fb327a9e7a90855165cdbce86a8a5fcf469b5475489e01c",
          "sha256": "bcdcbcb8710aed2258a6d15526a8a4372c6e3f7a4aa6dcde4400b06301621c49",
          "sha1": "6891f5fcdde933ced85d7abec673994bdeebea05",
          "md5": "941f5221af6044d51c4aed46d8ff18c5"
        }
      ]
    }
  ]
}
