{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-client/1.0.0-SNAPSHOT/subsonic-client-1.0.0-SNAPSHOT.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-client",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-linuxX64Main-1.0.0-SNAPSHOT.klib",
          "url": "subsonic-client-linuxx64-1.0.0-SNAPSHOT.klib",
          "size": 67221,
          "sha512": "1491938472a83e8d5f801749a6d570ff3c02eb88c63ab07ea06a473c2e86b976898ee7f8b6d04894a66c66c9b07c65fd7a9b50e8bbaaf18419abb4a07bb226a0",
          "sha256": "2d1f3c706d6a7293ec2472943c079350d5f59f93cad2a237a9505adeb306ab17",
          "sha1": "7b868e0279ce1efa8e29af34a35c49b6d02dc821",
          "md5": "d4bdb99ff1cae5c35ae38c8d85bcecf8"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-client-linuxx64-1.0.0-SNAPSHOT-sources.jar",
          "url": "subsonic-client-linuxx64-1.0.0-SNAPSHOT-sources.jar",
          "size": 8111,
          "sha512": "07f987b598ee52922cfb43df267ea27afd203d5c32105deadfddff10abefab66ae162cf6033f8b323fb327a9e7a90855165cdbce86a8a5fcf469b5475489e01c",
          "sha256": "bcdcbcb8710aed2258a6d15526a8a4372c6e3f7a4aa6dcde4400b06301621c49",
          "sha1": "6891f5fcdde933ced85d7abec673994bdeebea05",
          "md5": "941f5221af6044d51c4aed46d8ff18c5"
        }
      ]
    }
  ]
}
