{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta11/subsonic-api-1.0.0-beta11.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-watchosArm64Main-1.0.0-beta11.klib",
          "url": "subsonic-api-watchosarm64-1.0.0-beta11.klib",
          "size": 329547,
          "sha512": "22e9c5588e1e0885ac7136f185c2e9211c9e5239eabcb0bcfb964308da25acf1d95079d601de42dad992653bec4200a8911bc679e0840fa193c9092f8fe3f15c",
          "sha256": "56e3fc31150fc8e7b7e32581688ecf23f943e9c4bb14cf6b9984b61d039dbd88",
          "sha1": "f3d29e70f1e3b2e64b37cd9eb66315c672c2650a",
          "md5": "35e004f8d801c64fc2d35194019ea0a0"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-watchosarm64-1.0.0-beta11-sources.jar",
          "url": "subsonic-api-watchosarm64-1.0.0-beta11-sources.jar",
          "size": 29767,
          "sha512": "2bfb981919963dfe03bb8e45eb75e21c09b44a90d99385c9bba4017f85ed4bb5ff3cbd5d1e97d530b580d8ce8a7bf583580533bdb141acc4e3e2b930bb81a8e5",
          "sha256": "26ecd4ec831da4643de54905908a732b0162fe0b14ee066e7be9f80fdc201fc6",
          "sha1": "a1ac70553aa8ebbc6cf278a7d45ab643bca19447",
          "md5": "046dd316a95f201b7b8415d4fc58aa04"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-watchosarm64-1.0.0-beta11-metadata.jar",
          "url": "subsonic-api-watchosarm64-1.0.0-beta11-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
