{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta10/subsonic-api-1.0.0-beta10.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-mingwX64Main-1.0.0-beta10.klib",
          "url": "subsonic-api-mingwx64-1.0.0-beta10.klib",
          "size": 328980,
          "sha512": "629bf820cd760b7a5e230b34f3bdd1abdfa6b10731177d8cc31d73d79c56842e9f91507e095309dc7c886e775d9814a4489b3d8e3741141fa30b882543a2711a",
          "sha256": "e69447232769cd24a1160276c31ca8a9a2aa3a1b79de3ec814af64de4ccde953",
          "sha1": "d3ac1fa56446b271e7d2882229f9695524a7a36f",
          "md5": "68da030eb72b926bbe948d5ac5439e45"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-mingwx64-1.0.0-beta10-sources.jar",
          "url": "subsonic-api-mingwx64-1.0.0-beta10-sources.jar",
          "size": 29756,
          "sha512": "89ec5d460700dacacda3770fcaabfee39596b855e345195f12b3e184fe478550bb384625b15d07d6758fdd49564961345484d1102563d50fbdc00cd2ecb87156",
          "sha256": "ab4c45d206b5cf7ae055548f429a254f21ceafa54dd2f1fc35f868717a4fd7d9",
          "sha1": "8928b2b4da90a8ad385e2a31204ff617b0d70b72",
          "md5": "51c2fbe7e308d407cfaa076dba6e5233"
        }
      ]
    }
  ]
}
