{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zt64.subsonic",
    "module": "subsonic-client",
    "version": "1.0.0-beta10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.zt64.subsonic",
          "module": "subsonic-api",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-client-metadata-1.0.0-beta10.jar",
          "url": "subsonic-client-1.0.0-beta10.jar",
          "size": 9764,
          "sha512": "bccae069193ff885199d80800dbeffb4faf88c82b173b7215ae06e6bfce52d00cabc6327a038bc038a57498b13a4186396cfcdcab4ccb85a5cefd8466f90e739",
          "sha256": "c5dc3de35625f50088c904287f9e7bf2a41221589b6d3f43fad1e29f8a0722c8",
          "sha1": "f51a32ec765479d49b4c5bfae864874cc67d5dab",
          "md5": "36191b9bc7eaf3f94d78b85742e54d01"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "subsonic-client-kotlin-1.0.0-beta10-sources.jar",
          "url": "subsonic-client-1.0.0-beta10-sources.jar",
          "size": 7650,
          "sha512": "5a698e67bfbce4c658b94311f0382ceeb91c96e8be3fd3ae607cf81fa4667a75858dde79e785f58e504ad9be70f4b1fd55d318c9a391ce16d1fe573a721637a9",
          "sha256": "24ab6f2cd38e1d9ce5842fb8745f420c8d3e9c847d46fb99a4c422f6a29f7f09",
          "sha1": "379f7047ec0970d0501cf2c8f7558fddad7fcf45",
          "md5": "569a37f08aedfce9ededde8d77a452aa"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosarm64/1.0.0-beta10/subsonic-client-iosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosarm64/1.0.0-beta10/subsonic-client-iosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosarm64/1.0.0-beta10/subsonic-client-iosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iossimulatorarm64/1.0.0-beta10/subsonic-client-iossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iossimulatorarm64/1.0.0-beta10/subsonic-client-iossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iossimulatorarm64/1.0.0-beta10/subsonic-client-iossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosx64/1.0.0-beta10/subsonic-client-iosx64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosx64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosx64/1.0.0-beta10/subsonic-client-iosx64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosx64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-iosx64/1.0.0-beta10/subsonic-client-iosx64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-iosx64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-js/1.0.0-beta10/subsonic-client-js-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-js",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-js/1.0.0-beta10/subsonic-client-js-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-js",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-js/1.0.0-beta10/subsonic-client-js-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-js",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-client-jvm/1.0.0-beta10/subsonic-client-jvm-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-jvm",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-client-jvm/1.0.0-beta10/subsonic-client-jvm-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-jvm",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-client-jvm/1.0.0-beta10/subsonic-client-jvm-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-jvm",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-linuxarm64/1.0.0-beta10/subsonic-client-linuxarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-linuxarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-linuxarm64/1.0.0-beta10/subsonic-client-linuxarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-linuxarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-linuxx64/1.0.0-beta10/subsonic-client-linuxx64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-linuxx64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-linuxx64/1.0.0-beta10/subsonic-client-linuxx64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-linuxx64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-macosarm64/1.0.0-beta10/subsonic-client-macosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-macosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-macosarm64/1.0.0-beta10/subsonic-client-macosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-macosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-macosarm64/1.0.0-beta10/subsonic-client-macosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-macosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-mingwx64/1.0.0-beta10/subsonic-client-mingwx64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-mingwx64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-mingwx64/1.0.0-beta10/subsonic-client-mingwx64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-mingwx64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvosarm64/1.0.0-beta10/subsonic-client-tvosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvosarm64/1.0.0-beta10/subsonic-client-tvosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvosarm64/1.0.0-beta10/subsonic-client-tvosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvossimulatorarm64/1.0.0-beta10/subsonic-client-tvossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvossimulatorarm64/1.0.0-beta10/subsonic-client-tvossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-tvossimulatorarm64/1.0.0-beta10/subsonic-client-tvossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-tvossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-wasm-js/1.0.0-beta10/subsonic-client-wasm-js-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-wasm-js",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-wasm-js/1.0.0-beta10/subsonic-client-wasm-js-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-wasm-js",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-client-wasm-js/1.0.0-beta10/subsonic-client-wasm-js-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-wasm-js",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm32/1.0.0-beta10/subsonic-client-watchosarm32-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm32",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm32/1.0.0-beta10/subsonic-client-watchosarm32-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm32",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm32/1.0.0-beta10/subsonic-client-watchosarm32-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm32",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm64/1.0.0-beta10/subsonic-client-watchosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm64/1.0.0-beta10/subsonic-client-watchosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchosarm64/1.0.0-beta10/subsonic-client-watchosarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchosarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchossimulatorarm64/1.0.0-beta10/subsonic-client-watchossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchossimulatorarm64/1.0.0-beta10/subsonic-client-watchossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-client-watchossimulatorarm64/1.0.0-beta10/subsonic-client-watchossimulatorarm64-1.0.0-beta10.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-client-watchossimulatorarm64",
        "version": "1.0.0-beta10"
      }
    }
  ]
}
