{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta09/subsonic-api-1.0.0-beta09.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-linuxX64Main-1.0.0-beta09.klib",
          "url": "subsonic-api-linuxx64-1.0.0-beta09.klib",
          "size": 329145,
          "sha512": "a8cd30776b7c567f57047052f083a4f2da7e664e7fa5d6c6ecb7466ee7fb72670fbb4803696a08353b13bbedf997b05436a31a2c1c74cb90328c8dec304fcead",
          "sha256": "59003c960fce12926875329d103122094dbc13a0668f7486467871dd3e1ee1a8",
          "sha1": "ba481bb03e613961c4dbad84cbdf38a844d57e09",
          "md5": "12003fcf2e4d1b07054dbcf8aa1c694d"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "subsonic-api-linuxx64-1.0.0-beta09-sources.jar",
          "url": "subsonic-api-linuxx64-1.0.0-beta09-sources.jar",
          "size": 29792,
          "sha512": "9464122ba4ea101afac46f1c8c46e8c8eb7f37edf016ef2078e420ea36ca50ef4aa7baee90c919b50d3230565dbd228048b736dbb8d31893cf8994655e2cdb5f",
          "sha256": "aaf2d0e767767b1e08d45296d29b076a4f1266c9449ba2598a0bb56b4714f11b",
          "sha1": "6f949a29034a5a3c5f699b52bf8973e08edb54cb",
          "md5": "cd483bbe80471160775801fba090f3fc"
        }
      ]
    }
  ]
}
