{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-metadata-1.0.0-beta09.jar",
          "url": "subsonic-api-1.0.0-beta09.jar",
          "size": 45987,
          "sha512": "7bdcbe6e41640ce61ff04235da7bace7e896a80094d7b09d501a44621b31760c252b4838c7036003d129b2ac3c15ce64164b76d2085da1a55fdbaefcbc3c70c2",
          "sha256": "1c6a1c9eddd12db7c2fe47e2c4269e73ed66d58b43d97116022bd4a40dec042a",
          "sha1": "44aeab4ca70aaae967bcfb06e339f8bd20deb9a4",
          "md5": "8038772cdc649b242350a82cabab46bb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "subsonic-api-kotlin-1.0.0-beta09-sources.jar",
          "url": "subsonic-api-1.0.0-beta09-sources.jar",
          "size": 29771,
          "sha512": "ebd841ddbdc134348ab7058109af01f9107cf20bfc5208737a43318a072294f20fce393b9fef8433d26c151fb0aa8c241220a5c76259aa3e54913ae61f8b64c8",
          "sha256": "fa74d07c1b627546d58a59c7a85fffc97bfb1e1429887fcd49db31a04655a717",
          "sha1": "b1c78e893496a6883259d7d54b8082629bbfc6de",
          "md5": "fcdc649421b182f2cef83ac8a30617ff"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-beta09/subsonic-api-iosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-beta09/subsonic-api-iosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosarm64/1.0.0-beta09/subsonic-api-iosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-beta09/subsonic-api-iossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-beta09/subsonic-api-iossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iossimulatorarm64/1.0.0-beta09/subsonic-api-iossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-beta09/subsonic-api-iosx64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-beta09/subsonic-api-iosx64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-iosx64/1.0.0-beta09/subsonic-api-iosx64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-iosx64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-beta09/subsonic-api-js-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-beta09/subsonic-api-js-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-js/1.0.0-beta09/subsonic-api-js-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-js",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-beta09/subsonic-api-jvm-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-beta09/subsonic-api-jvm-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../subsonic-api-jvm/1.0.0-beta09/subsonic-api-jvm-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-jvm",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxarm64/1.0.0-beta09/subsonic-api-linuxarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxarm64/1.0.0-beta09/subsonic-api-linuxarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxx64/1.0.0-beta09/subsonic-api-linuxx64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxx64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-linuxx64/1.0.0-beta09/subsonic-api-linuxx64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-linuxx64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-beta09/subsonic-api-macosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-beta09/subsonic-api-macosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-macosarm64/1.0.0-beta09/subsonic-api-macosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-macosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-mingwx64/1.0.0-beta09/subsonic-api-mingwx64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-mingwx64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-mingwx64/1.0.0-beta09/subsonic-api-mingwx64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-mingwx64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-beta09/subsonic-api-tvosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-beta09/subsonic-api-tvosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvosarm64/1.0.0-beta09/subsonic-api-tvosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-beta09/subsonic-api-tvossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-beta09/subsonic-api-tvossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-tvossimulatorarm64/1.0.0-beta09/subsonic-api-tvossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-tvossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-beta09/subsonic-api-wasm-js-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-beta09/subsonic-api-wasm-js-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../subsonic-api-wasm-js/1.0.0-beta09/subsonic-api-wasm-js-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-wasm-js",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-beta09/subsonic-api-watchosarm32-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-beta09/subsonic-api-watchosarm32-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm32/1.0.0-beta09/subsonic-api-watchosarm32-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm32",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-beta09/subsonic-api-watchosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-beta09/subsonic-api-watchosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchosarm64/1.0.0-beta09/subsonic-api-watchosarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchosarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-beta09/subsonic-api-watchossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-beta09/subsonic-api-watchossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../subsonic-api-watchossimulatorarm64/1.0.0-beta09/subsonic-api-watchossimulatorarm64-1.0.0-beta09.module",
        "group": "dev.zt64.subsonic",
        "module": "subsonic-api-watchossimulatorarm64",
        "version": "1.0.0-beta09"
      }
    }
  ]
}
