{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta09/subsonic-api-1.0.0-beta09.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-beta09.klib",
          "url": "subsonic-api-js-1.0.0-beta09.klib",
          "size": 316351,
          "sha512": "790c889bc6d373d0d4dd40a6387af1475fafd13c10c8874dec5a0dca3716070cd7cc46d541a13888c8f2d7f708b6224e3b596cffd0b245dd8e83bf21db3f0bc3",
          "sha256": "afdafbbc8d2d94346d16e571e0e37af6455df0cf7679a7ee59435a9842507678",
          "sha1": "c62acd0d5be9c51f59b840dfa96dd4872b36dfeb",
          "md5": "ae448fa4b7f7c445f53c84ae0dce0172"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-beta09.klib",
          "url": "subsonic-api-js-1.0.0-beta09.klib",
          "size": 316351,
          "sha512": "790c889bc6d373d0d4dd40a6387af1475fafd13c10c8874dec5a0dca3716070cd7cc46d541a13888c8f2d7f708b6224e3b596cffd0b245dd8e83bf21db3f0bc3",
          "sha256": "afdafbbc8d2d94346d16e571e0e37af6455df0cf7679a7ee59435a9842507678",
          "sha1": "c62acd0d5be9c51f59b840dfa96dd4872b36dfeb",
          "md5": "ae448fa4b7f7c445f53c84ae0dce0172"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-beta09-sources.jar",
          "url": "subsonic-api-js-1.0.0-beta09-sources.jar",
          "size": 29771,
          "sha512": "ebd841ddbdc134348ab7058109af01f9107cf20bfc5208737a43318a072294f20fce393b9fef8433d26c151fb0aa8c241220a5c76259aa3e54913ae61f8b64c8",
          "sha256": "fa74d07c1b627546d58a59c7a85fffc97bfb1e1429887fcd49db31a04655a717",
          "sha1": "b1c78e893496a6883259d7d54b8082629bbfc6de",
          "md5": "fcdc649421b182f2cef83ac8a30617ff"
        }
      ]
    }
  ]
}
