{
  "formatVersion": "1.1",
  "component": {
    "url": "../../subsonic-api/1.0.0-beta09/subsonic-api-1.0.0-beta09.module",
    "group": "dev.zt64.subsonic",
    "module": "subsonic-api",
    "version": "1.0.0-beta09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-beta09.klib",
          "url": "subsonic-api-js-1.0.0-beta09.klib",
          "size": 316449,
          "sha512": "19d57f31410f0a9d08be86a9cfe9cd1ed83a655a1e921483ae65cc3060455c4dd7c07f2c943a00a08db275ed7586df20f23ab9e9943bdae8c98251f34b08a61a",
          "sha256": "c44eddea23999c33edee7ac7ca0ebeb99091e605c7f0a305f6ff163909cfdff4",
          "sha1": "39a63792435da232111a9ddcc274df1c84a40e4b",
          "md5": "67049e4a3a140a5f919193f6d302175a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "md",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-beta09.klib",
          "url": "subsonic-api-js-1.0.0-beta09.klib",
          "size": 316449,
          "sha512": "19d57f31410f0a9d08be86a9cfe9cd1ed83a655a1e921483ae65cc3060455c4dd7c07f2c943a00a08db275ed7586df20f23ab9e9943bdae8c98251f34b08a61a",
          "sha256": "c44eddea23999c33edee7ac7ca0ebeb99091e605c7f0a305f6ff163909cfdff4",
          "sha1": "39a63792435da232111a9ddcc274df1c84a40e4b",
          "md5": "67049e4a3a140a5f919193f6d302175a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "subsonic-api-js-1.0.0-beta09-sources.jar",
          "url": "subsonic-api-js-1.0.0-beta09-sources.jar",
          "size": 29792,
          "sha512": "9464122ba4ea101afac46f1c8c46e8c8eb7f37edf016ef2078e420ea36ca50ef4aa7baee90c919b50d3230565dbd228048b736dbb8d31893cf8994655e2cdb5f",
          "sha256": "aaf2d0e767767b1e08d45296d29b076a4f1266c9449ba2598a0bb56b4714f11b",
          "sha1": "6f949a29034a5a3c5f699b52bf8973e08edb54cb",
          "md5": "cd483bbe80471160775801fba090f3fc"
        }
      ]
    }
  ]
}
